<header>
<div class="container">
    <a href="#" data-activates="nav-mobile" class="button-collapse top-nav full hide-on-large-only">
        <i class="mdi-navigation-menu"></i>
    </a>
</div>
<ul id="nav-mobile" class="side-nav fixed" style="width: 240px;">
    <li class="logo">
        <a id="logo-container" href="http://materializecss.com/" class="brand-logo" style="text-align:center;">
            <?= Asset::img('admin/logo.jpg', ['style' => 'height:50px; margin:0 auto;']) ?>
        </a>
    </li>
    <li class="no-padding">
        <ul class="collapsible collapsible-accordion">
            <li class="bold"><a class="collapsible-header  waves-effect waves-teal">マスター管理</a>
                <div class="collapsible-body" style="">
                    <ul>
                        <li><a href="/admin/coupon_sites">クーポンサイト</a></li>
                    </ul>
                </div>
            </li>
        </ul>
    </li>
  </ul>
</header>